### ISSUE TITLE
Deprecated Version

### ISSUE THREAD

**Issue by agentoranger** [darkxex/UnCapFF5PRemaster#1]
Thank you for the work that goes into making this utility, it's been a while since an update and the utility is now deprecated in presence of the latest version of the game.

Have a good weekend.
-B

![image](https://user-images.githubusercontent.com/9388401/195956040-38c9754a-01ed-47c2-8540-e10c5a46e5ae.png)

**Comment by darkxex** [comment]
fixed https://github.com/darkxex/UnCapFF5PRemaster/releases/tag/1.6
